
#  Solution: 3 state Markov Chain {#mc-solution}
```{r, echo=FALSE, engine='tikz', out.width='90%', fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'png', engine.opts = list(template = "latex/tikz2pdf.tex")}
\begin{tikzpicture}[node distance=4cm,->,>=latex,auto,
  every edge/.append style={thick}]

  \node[state] (1) {Cloudy};
   \node[state] (2) [below left of =1] {Sunny};
  \node[state] (3) [below right of=1] {Rainy};


  \path (1) edge[loop above]  node{$?$} (1)
            edge[bend left =12]  node{$0.6$}   (2)
            edge[bend left = 12] node{$ 0.2$} (3)
        (2) edge[loop below] node{$?$}  (2)
            edge[bend left=12] node{$0.1$}     (1)
            edge[bend right = 12] node {$0.2$} (3)
        (3) edge[loop below] node{$?$} (3)
            edge[bend left = 15] node{$0.4$} (1)
            edge[bend right = 15] node{$0.3$} (2);
\end{tikzpicture}
```

Set up a 3x3 transition matrix:

```{r}
transitionMatrix = matrix(c(0.7, 0.2, 0.1,
                            0.3, 0.3, 0.4,
                            0.6, 0.2, 0.2), nrow=3, ncol=3, byrow=TRUE)

# Check matrix set-up correctly
print(transitionMatrix)

```

Note the ordering of the states is arbitrary but here we have used the convention that State 1 is Sunny, State 2 is Rainy and State 3 is Cloudy which means the probabilities are completed in that order in the transition matrix. We just need to be consistent.

```{r}
state <- 1 # initial state - it is [1] sunny, [2] rainy and [3] cloudy
weather_sequence <- rep(0, 30) # vector to store simulated values

# simulate for 30 days
for (day in 1:30) {
  pr <- transitionMatrix[state, ] # select the row of transition probabilities

  # sample [1-3] based on the probs pr
  state <- sample(c(1, 2, 3), size = 1, prob = pr)
  weather_sequence[day] <- state # store the sampled state
}
print(weather_sequence)
```
